namespace Steepshot.Core.Models.Enums
{
    public enum ActionType
    {
        Like,
        Flag,
        More,
        Profile,
        Comments,
        Voters,
        VotersLikes,
        VotersFlags,
        Flagers,
        Preview,
        Reply,
        Follow,
        Tap,
        Delete,
        Edit,
        Hide,
        Photo,
        Share,
        Close,
        Followers,
        Following,
        Balance,
        LikePower,
        ProfilePower,
        Transfer,
    }
}
